### ISSUE TITLE
custom domains for hosting

### ISSUE THREAD

**Issue by joshbalfour** [ultimaup/ultima#18]
- [x] .ultima.yml change
```
api
  branch-domains:
    master: myproject.com
    develop: staging.myproject.com
web
  branch-domains:
     master: www.myproject.com
     develop: www.staging.myproject.com
```
- [x] update router-mgmt to use mapping
- [x] add ui to edit `.ultima.yml` with cnaming instructions to username.onultima.com, and testing
- [x] support moving a domain from one repo to another

- [x] use different cert resolver for aliases (can't use DNS)
- [x] May 25 11:04:36 pawnSteve traefik[118509]: time="2020-05-25T11:04:36+01:00" level=error msg="Unable to obtain ACME certificate for domains \"*.com,*.com\" : unable to generate a certificate for the domains [*.com *.com]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"*.com\": Domain name is a wildcard for an ICANN TLD, url: " providerName=myresolver.acme
